name: 'Action Test'
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - "**.ts"
      - ".github/workflows/action_check.yml"
      - "action.yml"
      - "dist/index.js"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Action
        uses: actions/checkout@v2
        with:
          path: action
      
      - run: |
          pwd
          ls -l
          ls -l ./action

      - name: Checkout Example Repo
        uses: actions/checkout@v2
        with:
          repository: Cyb3r-Jak3/worker-example-project
      
      - name: Successful Action
        uses: action
        with:
          apiToken: ${{ secrets.TEST_TOKEN }}
          secrets: |
            HELLO
        env:
          HELLO: ${{ secrets.HELLO }}

