name: 'Action Test'
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - "**.ts"
      - ".github/workflows/action_check.yml"
      - "action.yml"
      - "dist/index.js"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repository }}@${{ github.base_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
      - name: Checkout Example Repo
        uses: actions/checkout@v2
        with:
          repository: Cyb3r-Jak3/worker-example-project
      
      - name: Successful Action
        # uses: ${{ github.repository }}@${{ github.head_ref }}
        uses: Cyb3r-Jak3/wrangler-action-javascript@dev
        with:
          apiToken: ${{ secrets.TEST_TOKEN }}
          secrets: |
            HELLO
        env:
          HELLO: WORLD

